//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOwner
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Cannot be empty")]
        public string Firstname { get; set; }

        [Required(ErrorMessage = "Cannot be empty")]

        public string Lastname { get; set; }


        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Cannot be empty")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                            @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                            @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                            ErrorMessage = "Email is not valid")]

        public string Email { get; set; }


        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Cannot be empty")]
        [StringLength(15, ErrorMessage = "Password must be 8 characters long", MinimumLength = 8)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Cannot be empty")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Cannot be empty")]
        public string Address { get; set; }
    }
}
